services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HEALTHDELTA_VERSION: "0.0.0+dev"
        HEALTHDELTA_GIT_SHA: "local"
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
