#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_DIR="${DEPLOY_DIR:-/opt/healthdelta}"
SERVICE_NAME="${SERVICE_NAME:-backend}"
BASE_URL="${BASE_URL:-http://127.0.0.1:8080}"
PUBLISHED_BIND_HOST="${HEALTHDELTA_PUBLISHED_BIND_HOST:-127.0.0.1}"
OLLAMA_BASE_URL="${HEALTHDELTA_OLLAMA_BASE_URL:-}"
OLLAMA_MODEL="${HEALTHDELTA_OLLAMA_MODEL:-llama3.2:latest}"
OLLAMA_TIMEOUT_S="${HEALTHDELTA_OLLAMA_TIMEOUT_S:-20}"
OLLAMA_NUM_GPU="${HEALTHDELTA_OLLAMA_NUM_GPU:-0}"

ROLLBACK_TAG="${ROLLBACK_TAG:?rollback tag (e.g., v0.0.5)}"
ROLLBACK_VERSION="${ROLLBACK_VERSION:-${ROLLBACK_TAG#v}}"
ROLLBACK_SHA="${ROLLBACK_SHA:?rollback git sha}"

if [ ! -d "$DEPLOY_DIR" ]; then
  echo "ERROR: deploy dir '$DEPLOY_DIR' is missing" >&2
  exit 2
fi
if [ ! -w "$DEPLOY_DIR" ]; then
  echo "ERROR: deploy dir '$DEPLOY_DIR' is not writable by user '$(id -un)'" >&2
  exit 2
fi

cat >"$DEPLOY_DIR/.env" <<EOF
HEALTHDELTA_BACKEND_IMAGE_TAG=$ROLLBACK_TAG
HEALTHDELTA_PUBLISHED_BIND_HOST=$PUBLISHED_BIND_HOST
HEALTHDELTA_OLLAMA_BASE_URL=$OLLAMA_BASE_URL
HEALTHDELTA_OLLAMA_MODEL=$OLLAMA_MODEL
HEALTHDELTA_OLLAMA_TIMEOUT_S=$OLLAMA_TIMEOUT_S
HEALTHDELTA_OLLAMA_NUM_GPU=$OLLAMA_NUM_GPU
EOF

cd "$DEPLOY_DIR"
docker compose --env-file .env pull "$SERVICE_NAME"
docker compose --env-file .env up -d --remove-orphans

DEPLOY_DIR="$DEPLOY_DIR" SERVICE_NAME="$SERVICE_NAME" BASE_URL="$BASE_URL" \
  FIXTURE_INPUT_PATH="/app/deploy/fixtures/profile_export" \
  EXPECTED_TAG="$ROLLBACK_TAG" EXPECTED_VERSION="$ROLLBACK_VERSION" EXPECTED_SHA="$ROLLBACK_SHA" \
  bash "$REPO_ROOT/scripts/cd/orin_verify_backend.sh"
